// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import CombinedBanner from './CombinedBanner';
import Contact from './Contact';
import ContentAutoSlider from './ContentAutoSlider';
import ContentTypeA from './ContentTypeA';
import ContentTypeB from './ContentTypeB';
import ContentTypeC from './ContentTypeC';
import CustomBlock from './CustomBlock';
import CustomGrid from './CustomGrid';
import Data from './Data';
import FullImageHero from './FullImageHero';
import Grid from './Grid';
import GridLogos from './GridLogos';
import Hero from './Hero';
import HomeHero from './HomeHero';
import JobBanner from './JobBanner';
import ListContent from './ListContent';
import Menu from './Menu';
import NoLinkSlider from './NoLinkSlider';
import Product from './Product';
import ServiceIntro from './ServiceIntro';
import SimpleContent from './SimpleContent';
import Slider from './Slider';
import StickyCard from './StickyCard';
import TextCard from './TextCard';

export {
	Accordion,
	CombinedBanner,
	Contact,
	ContentAutoSlider,
	ContentTypeA,
	ContentTypeB,
	ContentTypeC,
	CustomBlock,
	CustomGrid,
	Data,
	FullImageHero,
	Grid,
	GridLogos,
	Hero,
	HomeHero,
	JobBanner,
	ListContent,
	Menu,
	NoLinkSlider,
	Product,
	ServiceIntro,
	SimpleContent,
	Slider,
	StickyCard,
	TextCard,
};

export const components = {
	accordion: Accordion,
	combined_banner: CombinedBanner,
	contact: Contact,
	content_auto_slider: ContentAutoSlider,
	content_type_a: ContentTypeA,
	content_type_b: ContentTypeB,
	content_type_c: ContentTypeC,
	custom_block: CustomBlock,
	custom_grid: CustomGrid,
	data: Data,
	full_image_hero: FullImageHero,
	grid: Grid,
	grid_logos: GridLogos,
	hero: Hero,
	home_hero: HomeHero,
	job_banner: JobBanner,
	list_content: ListContent,
	menu: Menu,
	no_link_slider: NoLinkSlider,
	product: Product,
	service_intro: ServiceIntro,
	simple_content: SimpleContent,
	slider: Slider,
	sticky_card: StickyCard,
	text_card: TextCard,
};
